config:
  images_path: "data/parking/images/"
  K_path: "data/parking/K.txt"
  basline_images: [0,2]
  resize: False
  Initialization:
    ShiTomasi_params:
      maxCorners: 1000
      qualityLevel: 0.01
      minDistance: 7
      blockSize: 7
    KLT_params: 
      winSize: [49, 49]
      maxLevel: 7
      EPS: 10
      COUNT: 0.03

  Continuous:
    ShiTomasi_params:
      maxCorners: 1000
      qualityLevel: 0.01
      minDistance: 7
      blockSize: 7
    KLT_params: 
      winSize: [49, 49]
      maxLevel: 7
      EPS: 10
      COUNT: 0.03
    angle_threshold: 5 
    remove_similar: True # boolean value
    plot_x_scale: [0, 50]
    plot_y_scale: [100, 100]
